name: "glann_for_single_image"
sz: 28
nc: 1
glo:
  learning_rate: 0.005
  factor: 0.1
  nz: 256
  batch_size: 1
  decay: 20
  total_epoch: 300
  is_cuda : False
icp:
  dim: 32
  total_epoch: 50
fid:
  batch_size: 50
  n_images: 10000
